
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Herlambangsb
 */
public class Frame1 extends javax.swing.JFrame {
    String temp = "";
    Double ti,bt,h1;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        txtinggi = new javax.swing.JTextField();
        txberat = new javax.swing.JTextField();
        rbperempuan = new javax.swing.JRadioButton();
        rblaki = new javax.swing.JRadioButton();
        btnhitung = new javax.swing.JButton();
        btncoba = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txberatideal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txhasil = new javax.swing.JTextField();
        txsaran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 110, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 60, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 70, 14);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 90, 14);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 80, 14);

        jLabel6.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 270, 180, 14);
        getContentPane().add(txnama);
        txnama.setBounds(130, 60, 170, 30);
        getContentPane().add(txtinggi);
        txtinggi.setBounds(130, 100, 50, 30);
        getContentPane().add(txberat);
        txberat.setBounds(130, 140, 50, 30);

        buttonGroup1.add(rbperempuan);
        rbperempuan.setText("Perempuan");
        getContentPane().add(rbperempuan);
        rbperempuan.setBounds(120, 180, 100, 23);

        buttonGroup1.add(rblaki);
        rblaki.setText("Laki - laki");
        getContentPane().add(rblaki);
        rblaki.setBounds(230, 180, 100, 23);

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnhitung);
        btnhitung.setBounds(30, 220, 90, 23);

        btncoba.setText("Coba Lagi");
        btncoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobaActionPerformed(evt);
            }
        });
        getContentPane().add(btncoba);
        btncoba.setBounds(150, 220, 120, 23);

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar);
        btnkeluar.setBounds(290, 220, 80, 23);

        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 310, 160, 14);
        getContentPane().add(txberatideal);
        txberatideal.setBounds(210, 260, 59, 30);

        jLabel8.setText("Kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 270, 30, 14);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 110, 30, 14);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 150, 20, 14);

        txhasil.setEditable(false);
        getContentPane().add(txhasil);
        txhasil.setBounds(30, 340, 340, 30);
        getContentPane().add(txsaran);
        txsaran.setBounds(30, 380, 340, 30);

        setBounds(0, 0, 416, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void btncobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobaActionPerformed
        // TODO add your handling code here:
        txnama.setText("");
        txtinggi.setText("");
        txberat.setText("");
        txberatideal.setText("");
        txhasil.setText("");
        txsaran.setText("");
        rbperempuan.setSelected(false);
        rblaki.setSelected(false);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btncobaActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        if (txnama.getText().equals("") || txtinggi.getText().equals("") || txberat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data harus diisikan semua");
        } else if (rbperempuan.isSelected() || rblaki.isSelected()) {
            try {
                Proses();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Inputam ada yang belum diisi");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Radio Button harus dipilih");
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncoba;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnkeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTextField txberat;
    private javax.swing.JTextField txberatideal;
    private javax.swing.JTextField txhasil;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txsaran;
    private javax.swing.JTextField txtinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(txtinggi.getText());
        bt = Double.parseDouble(txberat.getText());
        
        if(rbperempuan.isSelected()){
            h1 = (ti-100)*1;
        }
        else if(rblaki.isSelected()){
            h1 = (ti-104)*1;
        }
        temp = Double.toString(h1.intValue());
    
    
    if(h1<bt){
    txberatideal.setText(temp);
    txhasil.setText("Maaf "+ txnama.getText()+ ", Sepertinya berat anda Overweight");
    txsaran.setText("Banyaklah berolahraga dan hindari makanan kolesterol");
    }
    else if(h1>bt){
    txberatideal.setText(temp);
    txhasil.setText("Maaf "+ txnama.getText()+ ", Sepertinya berat anda Underweight");
    txsaran.setText("Banyaklah menkomsusi makanan yang berkarbohidtra");
    }
    else{
    txberatideal.setText(temp);
    txhasil.setText("Hallo "+ txnama.getText()+ ", Berat badan anda sudah ideal");
    txsaran.setText("Lanjutkan pola makan teratur");
}
    }
}
